import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"
import { AuthProvider } from "@/contexts/auth/providerAuth"
import { Toaster } from "react-hot-toast"
import { ProductProvider } from "@/contexts/product/providerProduct"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-blue-gray-50">
                <AuthProvider>
                    <ProductProvider>
                        <div className="relative mb-8 h-full w-full">
                            <div className="sticky top-0 z-[999] flex w-full items-center">
                                <Navbar />
                            </div>
                            <div className="px-6">
                                <div className="container mx-auto flex">
                                    <div className="mt-6 w-full flex justify-center">
                                        {children}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <Toaster />
                    </ProductProvider>
                </AuthProvider>
            </body>
        </html>
    )
}
